package cz.fi.muni.pa036.airticketbooking.entity;
// Generated 28-Apr-2015 10:09:55 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Airport generated by hbm2java
 */
public class Airport  implements java.io.Serializable {


     private int id;
     private City city;
     private String name;
     private String code;
     private Set flightsForAirportFromId = new HashSet(0);
     private Set flightsForAirportToId = new HashSet(0);

    public Airport() {
    }

	
    public Airport(int id, City city) {
        this.id = id;
        this.city = city;
    }
    public Airport(int id, City city, String name, String code, Set flightsForAirportFromId, Set flightsForAirportToId) {
       this.id = id;
       this.city = city;
       this.name = name;
       this.code = code;
       this.flightsForAirportFromId = flightsForAirportFromId;
       this.flightsForAirportToId = flightsForAirportToId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Set getFlightsForAirportFromId() {
        return this.flightsForAirportFromId;
    }
    
    public void setFlightsForAirportFromId(Set flightsForAirportFromId) {
        this.flightsForAirportFromId = flightsForAirportFromId;
    }
    public Set getFlightsForAirportToId() {
        return this.flightsForAirportToId;
    }
    
    public void setFlightsForAirportToId(Set flightsForAirportToId) {
        this.flightsForAirportToId = flightsForAirportToId;
    }




}


