package cz.fi.muni.pa036.airticketbooking.entity;
// Generated 28-Apr-2015 10:09:55 by Hibernate Tools 3.2.1.GA



/**
 * Baggage generated by hbm2java
 */
public class Baggage  implements java.io.Serializable {


     private Long id;
     private FlightTicket flightTicket;
     private String type;
     private Long amount;

    public Baggage() {
    }

	
    public Baggage(Long id, FlightTicket flightTicket) {
        this.id = id;
        this.flightTicket = flightTicket;
    }
    public Baggage(Long id, FlightTicket flightTicket, String type, Long amount) {
       this.id = id;
       this.flightTicket = flightTicket;
       this.type = type;
       this.amount = amount;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public FlightTicket getFlightTicket() {
        return this.flightTicket;
    }
    
    public void setFlightTicket(FlightTicket flightTicket) {
        this.flightTicket = flightTicket;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Long getAmount() {
        return this.amount;
    }
    
    public void setAmount(Long amount) {
        this.amount = amount;
    }




}


