package cz.fi.muni.pa036.airticketbooking.entity;
// Generated 28-Apr-2015 10:09:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Flight generated by hbm2java
 */
public class Flight  implements java.io.Serializable {


     private Long id;
     private Plane plane;
     private Airport airportByAirportToId;
     private Airport airportByAirportFromId;
     private String code;
     private Date departure;
     private Date arrival;
     private Set<FlightPrice> flightPrices = new HashSet(0);
     private Set<FlightTicket> flightTickets = new HashSet(0);

    public Flight() {
    }

	
    public Flight(Long id, Plane plane, Airport airportByAirportToId, Airport airportByAirportFromId) {
        this.id = id;
        this.plane = plane;
        this.airportByAirportToId = airportByAirportToId;
        this.airportByAirportFromId = airportByAirportFromId;
    }
    
    public Flight(Long id, Plane plane, Airport airportByAirportToId, Airport airportByAirportFromId, String code, Date departure, Date arrival, Set<FlightPrice> flightPrices, Set<FlightTicket> flightTickets) {
       this.id = id;
       this.plane = plane;
       this.airportByAirportToId = airportByAirportToId;
       this.airportByAirportFromId = airportByAirportFromId;
       this.code = code;
       this.departure = departure;
       this.arrival = arrival;
       this.flightPrices = flightPrices;
       this.flightTickets = flightTickets;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Plane getPlane() {
        return this.plane;
    }
    
    public void setPlane(Plane plane) {
        this.plane = plane;
    }
    public Airport getAirportByAirportToId() {
        return this.airportByAirportToId;
    }
    
    public void setAirportByAirportToId(Airport airportByAirportToId) {
        this.airportByAirportToId = airportByAirportToId;
    }
    public Airport getAirportByAirportFromId() {
        return this.airportByAirportFromId;
    }
    
    public void setAirportByAirportFromId(Airport airportByAirportFromId) {
        this.airportByAirportFromId = airportByAirportFromId;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Date getDeparture() {
        return this.departure;
    }
    
    public void setDeparture(Date departure) {
        this.departure = departure;
    }
    public Date getArrival() {
        return this.arrival;
    }
    
    public void setArrival(Date arrival) {
        this.arrival = arrival;
    }
    public Set<FlightPrice> getFlightPrices() {
        return this.flightPrices;
    }
    
    public void setFlightPrices(Set<FlightPrice> flightPrices) {
        this.flightPrices = flightPrices;
    }
    public Set<FlightTicket> getFlightTickets() {
        return this.flightTickets;
    }
    
    public void setFlightTickets(Set<FlightTicket> flightTickets) {
        this.flightTickets = flightTickets;
    }




}


