package cz.fi.muni.pa036.airticketbooking.entity;
// Generated 28-Apr-2015 10:09:55 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * FlightTicket generated by hbm2java
 */
public class FlightTicket  implements java.io.Serializable {


     private int id;
     private Flight flight;
     private Integer nextFlightTicket;
     private String passangerName;
     private String passangerSurname;
     private String passangerMiddleName;
     private String passangerTitle;
     private String passangerResidance;
     private String passangerIdNumeric;
     private String passangerPhoneNumeric;
     private Character checkedIn;
     private Set flightTicketPrices = new HashSet(0);
     private Set seatReservations = new HashSet(0);
     private Set baggages = new HashSet(0);

    public FlightTicket() {
    }

	
    public FlightTicket(int id, Flight flight) {
        this.id = id;
        this.flight = flight;
    }
    public FlightTicket(int id, Flight flight, Integer nextFlightTicket, String passangerName, String passangerSurname, String passangerMiddleName, String passangerTitle, String passangerResidance, String passangerIdNumeric, String passangerPhoneNumeric, Character checkedIn, Set flightTicketPrices, Set seatReservations, Set baggages) {
       this.id = id;
       this.flight = flight;
       this.nextFlightTicket = nextFlightTicket;
       this.passangerName = passangerName;
       this.passangerSurname = passangerSurname;
       this.passangerMiddleName = passangerMiddleName;
       this.passangerTitle = passangerTitle;
       this.passangerResidance = passangerResidance;
       this.passangerIdNumeric = passangerIdNumeric;
       this.passangerPhoneNumeric = passangerPhoneNumeric;
       this.checkedIn = checkedIn;
       this.flightTicketPrices = flightTicketPrices;
       this.seatReservations = seatReservations;
       this.baggages = baggages;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Flight getFlight() {
        return this.flight;
    }
    
    public void setFlight(Flight flight) {
        this.flight = flight;
    }
    public Integer getNextFlightTicket() {
        return this.nextFlightTicket;
    }
    
    public void setNextFlightTicket(Integer nextFlightTicket) {
        this.nextFlightTicket = nextFlightTicket;
    }
    public String getPassangerName() {
        return this.passangerName;
    }
    
    public void setPassangerName(String passangerName) {
        this.passangerName = passangerName;
    }
    public String getPassangerSurname() {
        return this.passangerSurname;
    }
    
    public void setPassangerSurname(String passangerSurname) {
        this.passangerSurname = passangerSurname;
    }
    public String getPassangerMiddleName() {
        return this.passangerMiddleName;
    }
    
    public void setPassangerMiddleName(String passangerMiddleName) {
        this.passangerMiddleName = passangerMiddleName;
    }
    public String getPassangerTitle() {
        return this.passangerTitle;
    }
    
    public void setPassangerTitle(String passangerTitle) {
        this.passangerTitle = passangerTitle;
    }
    public String getPassangerResidance() {
        return this.passangerResidance;
    }
    
    public void setPassangerResidance(String passangerResidance) {
        this.passangerResidance = passangerResidance;
    }
    public String getPassangerIdNumeric() {
        return this.passangerIdNumeric;
    }
    
    public void setPassangerIdNumeric(String passangerIdNumeric) {
        this.passangerIdNumeric = passangerIdNumeric;
    }
    public String getPassangerPhoneNumeric() {
        return this.passangerPhoneNumeric;
    }
    
    public void setPassangerPhoneNumeric(String passangerPhoneNumeric) {
        this.passangerPhoneNumeric = passangerPhoneNumeric;
    }
    public Character getCheckedIn() {
        return this.checkedIn;
    }
    
    public void setCheckedIn(Character checkedIn) {
        this.checkedIn = checkedIn;
    }
    public Set getFlightTicketPrices() {
        return this.flightTicketPrices;
    }
    
    public void setFlightTicketPrices(Set flightTicketPrices) {
        this.flightTicketPrices = flightTicketPrices;
    }
    public Set getSeatReservations() {
        return this.seatReservations;
    }
    
    public void setSeatReservations(Set seatReservations) {
        this.seatReservations = seatReservations;
    }
    public Set getBaggages() {
        return this.baggages;
    }
    
    public void setBaggages(Set baggages) {
        this.baggages = baggages;
    }




}


