package cz.fi.muni.pa036.airticketbooking.entity;
// Generated 28-Apr-2015 10:09:55 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Seat generated by hbm2java
 */
public class Seat  implements java.io.Serializable {


     private int id;
     private Plane plane;
     private Integer numeric;
     private Character nextToWindow;
     private Character inTheMiddle;
     private Character nextToAisle;
     private Character firstClass;
     private Character secondClass;
     private Character businessClass;
     private Character economyClass;
     private Character disabledSeating;
     private Set seatReservations = new HashSet(0);

    public Seat() {
    }

	
    public Seat(int id, Plane plane) {
        this.id = id;
        this.plane = plane;
    }
    public Seat(int id, Plane plane, Integer numeric, Character nextToWindow, Character inTheMiddle, Character nextToAisle, Character firstClass, Character secondClass, Character businessClass, Character economyClass, Character disabledSeating, Set seatReservations) {
       this.id = id;
       this.plane = plane;
       this.numeric = numeric;
       this.nextToWindow = nextToWindow;
       this.inTheMiddle = inTheMiddle;
       this.nextToAisle = nextToAisle;
       this.firstClass = firstClass;
       this.secondClass = secondClass;
       this.businessClass = businessClass;
       this.economyClass = economyClass;
       this.disabledSeating = disabledSeating;
       this.seatReservations = seatReservations;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Plane getPlane() {
        return this.plane;
    }
    
    public void setPlane(Plane plane) {
        this.plane = plane;
    }
    public Integer getNumeric() {
        return this.numeric;
    }
    
    public void setNumeric(Integer numeric) {
        this.numeric = numeric;
    }
    public Character getNextToWindow() {
        return this.nextToWindow;
    }
    
    public void setNextToWindow(Character nextToWindow) {
        this.nextToWindow = nextToWindow;
    }
    public Character getInTheMiddle() {
        return this.inTheMiddle;
    }
    
    public void setInTheMiddle(Character inTheMiddle) {
        this.inTheMiddle = inTheMiddle;
    }
    public Character getNextToAisle() {
        return this.nextToAisle;
    }
    
    public void setNextToAisle(Character nextToAisle) {
        this.nextToAisle = nextToAisle;
    }
    public Character getFirstClass() {
        return this.firstClass;
    }
    
    public void setFirstClass(Character firstClass) {
        this.firstClass = firstClass;
    }
    public Character getSecondClass() {
        return this.secondClass;
    }
    
    public void setSecondClass(Character secondClass) {
        this.secondClass = secondClass;
    }
    public Character getBusinessClass() {
        return this.businessClass;
    }
    
    public void setBusinessClass(Character businessClass) {
        this.businessClass = businessClass;
    }
    public Character getEconomyClass() {
        return this.economyClass;
    }
    
    public void setEconomyClass(Character economyClass) {
        this.economyClass = economyClass;
    }
    public Character getDisabledSeating() {
        return this.disabledSeating;
    }
    
    public void setDisabledSeating(Character disabledSeating) {
        this.disabledSeating = disabledSeating;
    }
    public Set getSeatReservations() {
        return this.seatReservations;
    }
    
    public void setSeatReservations(Set seatReservations) {
        this.seatReservations = seatReservations;
    }




}


