package cz.fi.muni.pa036.airticketbooking.entity;
// Generated 28-Apr-2015 10:09:55 by Hibernate Tools 3.2.1.GA



/**
 * SeatReservation generated by hbm2java
 */
public class SeatReservation  implements java.io.Serializable {


     private Long id;
     private FlightTicket flightTicket;
     private Seat seat;

    public SeatReservation() {
    }

    public SeatReservation(Long id, FlightTicket flightTicket, Seat seat) {
       this.id = id;
       this.flightTicket = flightTicket;
       this.seat = seat;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public FlightTicket getFlightTicket() {
        return this.flightTicket;
    }
    
    public void setFlightTicket(FlightTicket flightTicket) {
        this.flightTicket = flightTicket;
    }
    public Seat getSeat() {
        return this.seat;
    }
    
    public void setSeat(Seat seat) {
        this.seat = seat;
    }




}


